### ISSUE TITLE
Generalização de código

### ISSUE THREAD

**Issue by horchulhack** [patrickerson/calculadora-notas#1]
https://github.com/patrickerson/calculadora-notas/blob/c7e116f853ab3ad417dd08512e530313ccb6c3ca/main.py#L9-L15

Acho que nesse trecho de código dá pra fazer o seguinte:

```
 a = notas.iloc[0,4:] 
 notas_limpas = [] 
 for i in range(0, len(a)): 
     number = a[i].split("/") 
     divisao = int(number[0]) / int(number[1]) 
     nota_limpa = divisao 
     notas_limpas.append(nota_limpa) 
```

colocar um len() dentro do range que pega o total de notas que você quer calcular mais o peso delas. Assim creio que o código fique mais genérico e dê pra usar em qualquer disciplina.

Fica uma ideia aí!

**Comment by patrickerson** [comment]
Bem interessante, não tinha pensado em deixar ele para as outras disciplinas, mas gostei da ideia.
